# **DETERMINAN**

adalah ukuran skalar dari sebuah matriks atau selisih antara perkalian elemen-elemen pada diagonal utama dengan perkalian elemen-elemen pada diagonal sekunder.

## **Sifat-sifat determinan :**
1. Determinan dari matrix identitas adalah 1  
contoh :

In [4]:
import numpy as np
a = np.array([[4,2],[3,1]])
b = np.array([[4,1,3],[6,2,5],[8,4,5]])
c = np.array([[1,0],[0,1]])
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a,"\n")
print(b)

[[4 2]
 [3 1]] 

[[4 1 3]
 [6 2 5]
 [8 4 5]]


In [8]:
# a invers
ainv = np.invert (a)
ainv

array([[-5, -3],
       [-4, -2]])

In [15]:
# b invers
binv = np.invert(b)
binv

array([[-5, -2, -4],
       [-7, -3, -6],
       [-9, -5, -6]])

2. Misalkan a dan b adalah matriks bujur sangakar, maka  
det (c) = det (a) * det (b)  
det (I) = det (a) * det (a inv)  


In [24]:
# determinan a
det_a = np.linalg.det(a)
print(f"Determinan A = {det_a}")

Determinan A = -2.0


In [19]:
# determinan a invers
det_ainv = 1 / det_a
det_ainv

-0.5

In [23]:
# determinan b
det_b = np.linalg.det(b)
print(f"Determinan B = {det_b}")

Determinan B = -6.0


In [16]:
# determinan b invers
det_binv = 1 / det_b
det_binv

-0.16666666666666666

In [20]:
hasil = (det_a * det_ainv) * (det_b *det_binv)
print(hasil)

1.0


3. Merubah baris atau kolom dari matriks maka akan merubah tanda dari determinan

In [22]:
e = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(e, "\n")
det_e = round(np.linalg.det(e))
print(f"Determinan E = {det_e}")

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

Determinan E = 5


In [26]:
#merubah baris dari matriks
f = np.array([[1,1,1],[1,4,2],[3,2,1]])
print(f,"\n")
det_f = round(np.linalg.det(f))
print(f"Determinan F = {det_f}")

[[1 1 1]
 [1 4 2]
 [3 2 1]] 

Determinan F = -5


4. Jika baris/kolom merupakan kelipatan dari baris/kolom yang lain maka determinannya adalah 0

In [28]:
# baris 2 merupakan kelipatan dari baris 1
g = np.array([[1,4,2],[2,8,4],[3,2,1]])
print(g, "\n")
det_g = round(np.linalg.det(g))
print(f"Determinan G = {det_g}")

[[1 4 2]
 [2 8 4]
 [3 2 1]] 

Determinan G = 0


In [29]:
# kolom 2 merupakan kelipatan dari kolom 1
g = np.array([[1,4,2],[2,8,3],[1,4,1]])
print(g, "\n")
det_g = round(np.linalg.det(g))
print(f"Determinan G = {det_g}")

[[1 4 2]
 [2 8 3]
 [1 4 1]] 

Determinan G = 0


5. Jika K = Skalar dan Anxn memiliki nxn maka,  
det (KA) = K^n * det(A)

In [35]:
det_KA = (2**3) * 5
print(f"Determinan KA = {det_KA}")

Determinan KA = 40


In [36]:
# Pembuktian
ke = np.array([[2,8,4],[2,2,2],[6,4,2]])
print(ke, "\n")
det_ke = round(np.linalg.det(ke))
print(f"Determinan ke = {det_ke}")

[[2 8 4]
 [2 2 2]
 [6 4 2]] 

Determinan ke = 40


6. Jika T = Skalar dan  
$$
\begin{equation}  B=
\left[ \begin{array}{cccc} ta&tb&tc\\
d&e&f\\
g&h&i \end{array}\right]
\end{equation}
$$   
$$
\begin{equation} A =
\left[ \begin{array}{cccc} a&b&c\\
d&e&f\\
g&h&i \end{array}\right]
\end{equation}
$$   
det (B) = t * det(A)

In [37]:
h = np.array([[2,8,4],[1,1,1],[3,2,1]])
print(h, "\n")
det_h = round(np.linalg.det(e))
print(f"Determinan H = {det_h}")

[[2 8 4]
 [1 1 1]
 [3 2 1]] 

Determinan H = 5


7. Matriks segitiga atas adalah matriks bujursangkar yang semua entri dibawah diagonal utama bernilai nol.  
$$
\begin{equation} A =
\left[ \begin{array}{cccc} d1& . & .\\
0&d2&.\\
0&0&dn \end{array}\right]
\end{equation}
$$  
det (A) = d1, d2, ... ,dn
Determinan dari matriks segitiga atas adalah hasil perkalian dari setiap elemen diaogonal

In [38]:
a = np.array([[1,4,2],[0,4,1],[0,0,1]])
print(a, "\n")
det_a = round(np.linalg.det(a))
print(f"Determinan a = {det_a}")

[[1 4 2]
 [0 4 1]
 [0 0 1]] 

Determinan a = 4


8. Melakukan operasi baris elementer terhadap suatu baris tidak akan merubah determinan dan inversnya

In [39]:
a = np.array([[1,4,2],[0,-3,-1],[3,2,1]])
print(a, "\n")
det_a = round(np.linalg.det(a))
print(f"Determinan a = {det_a}")

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]] 

Determinan a = 5


9. det (A) = det (A Tranpuse)

In [42]:
e = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(e, "\n")
det_e = round(np.linalg.det(e))
print(f"Determinan e = {det_e}")

[[1 4 2]
 [1 1 1]
 [3 2 1]] 

Determinan e = 5


In [43]:
# determinan e tranpose
e_tran = e.transpose()
print(e_tran,"\n")
det_etran = round(np.linalg.det(e_tran))
print(f"Determinan e tranpose = {det_etran}")

[[1 1 3]
 [4 1 2]
 [2 1 1]] 

Determinan e tranpose = 5


## **Ekspansi Kofaktor**

In [44]:
e = np.array([[4,3,2,1],[1,1,1,1],[2,3,1,2],[4,4,2,1]])
print(e, "\n")
det_e = round(np.linalg.det(e))
print(f"Determinan e = {det_e}")

[[4 3 2 1]
 [1 1 1 1]
 [2 3 1 2]
 [4 4 2 1]] 

Determinan e = 3


In [45]:
e = np.array([[1,0,0,0],[0,1,0,1],[1,0,0,0],[0,1,2,1]])
print(e, "\n")
det_e = round(np.linalg.det(e))
print(f"Determinan e = {det_e}")

[[1 0 0 0]
 [0 1 0 1]
 [1 0 0 0]
 [0 1 2 1]] 

Determinan e = 0


In [46]:
a = np.array([[4,2,3,2],[2,3,3,2],[1,4,3,2],[1,2,2,1]])
print(a, "\n")
det_a = round(np.linalg.det(a))
print(f"Determinan e = {det_a}")

[[4 2 3 2]
 [2 3 3 2]
 [1 4 3 2]
 [1 2 2 1]] 

Determinan e = 1


Jadi determinannya adalah 1