# **EIGEN VECTOR & EIGEN VALUE**

### **Pengertian** :
Misalkan A adalah matrik bujur sangkar dengan derat n. JIka terdapat vektor tidak nol x dan skalar λ sehingga   

$Ax =λx$   

maka λ disebut eigenvalue dari A, dan x disebut eigenvector, yang nilainya bersesuai dengan eigenvalue λ.  
 
$Ax =λx$  

Ax : vektor x setelah transformasi linier   
λx : perkalian bilangan riel dari x, i.e. peregangan dari vektor x.   
Transformasi linier untuk eigenvector menghasilkan peregangan vektor sebanyak eigenvalue kali.

Transformasi linier A untuk vektor eigen x setara dengan transformasi linier peregangan λI.   

$Ax =λI x$
                   
Dua transformasi linier untuk vektor x ekuivalen, 

$(A −λI)x = 0.$     

Oleh karena itu, vektor x berada di ruang nol matriks (A − λI). Untuk membuat persamaan linier ini memiliki solusi bukan nol (yaitu membuat dimensi ruang nol bukan nol), matriks (A − λI) tidak boleh berupa matriks rank penuh (full rank) Dinyatakan dalam bentuk determinan:   

$det(A −λI) = 0$

### **Matriks 2x2**
Misalkan ada matriks $A$ berikut:

$A$ = $\begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}$

Hasilnya adalah polinomial karakteristik:

$A$ - $\lambda$ $I$ = $\begin{vmatrix} 1 - \lambda & 2 \\ 2 & 1 - \lambda \end{vmatrix}$ = $\lambda$^2 - 2 $\lambda$ - 3.


Akar-akarnya adalah $\lambda$ = 3 dan $\lambda$ = -1, yang merupakan nilai-nilai eigen dari $A$.

Untuk $\lambda$ = 3, substitusi ke dalam $A - 3I$ menghasilkan:

$A - 3I$ = $\begin{bmatrix} 1-3 & 2 \\ 2 & 1-3 \end{bmatrix}$ = $\begin{bmatrix} -2 & 2 \\ 2 & -2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$

Jadi, vektor eigen untuk $\lambda$ = 3 :

$v_1 = k \begin{bmatrix} 1 \\ 1 \end{bmatrix}.$

Untuk $\lambda$ = -1, substitusi ke dalam $A + I$ menghasilkan:

$A + I$ = $\begin{bmatrix} 1+1 & 2 \\ 2 & 1+1 \end{bmatrix}$ = $\begin{bmatrix} 2 & 2 \\ 2 & 2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$

Jadi, vektor eigen untuk $\lambda$ = 1 :

$v_2 = k \begin{bmatrix} 1 \\ -1 \end{bmatrix}.$

Jadi, vektor  $\begin{bmatrix} 1 \\ 1 \end{bmatrix}$ adalah vektor eigen yang berhubungan dengan nilai eigen $\lambda = 3$, dan vektor $ \begin{bmatrix} 1 \\ -1 \end{bmatrix} $ adalah vektor eigen yang berhubungan dengan nilai eigen $\lambda = 1$.

In [1]:
# Perhitungan menggunakan numpy
import numpy as np
from numpy import linalg as LA

a = np.array([[1,2],[2,1]])
print(a)
w, v = LA.eig(a)
print("e-value : \n",w)
print("e-vactor : \n",v.round())

[[1 2]
 [2 1]]
e-value : 
 [ 3. -1.]
e-vactor : 
 [[ 1. -1.]
 [ 1.  1.]]


### **Matriks 3x3**

Misalkan matriks $ A $ :

A = $\begin{bmatrix} 1 & 2 & 2 \\ 2 & 1 & 2 \\ 2 & 1 & 2 \end{bmatrix}$

Langkah 1: Temukan Nilai Eigen

Untuk menemukan nilai eigen $ \lambda $, kita perlu menghitung polinomial karakteristik yang diperoleh dari determinan matriks $ A - \lambda I $:

$A - \lambda I = \begin{bmatrix} 1 - \lambda & 2 & 2 \\ 2 & 1 - \lambda & 2 \\ 2 & 1 & 2 - \lambda \end{bmatrix} $

Polinomial karakteristiknya adalah:

$\det(A - \lambda I) = 0 $

Mari kita hitung determinan dari matriks tersebut. Untuk matriks 3x3, determinannya dapat dihitung menggunakan ekspansi kofaktor:

$\det(A - \lambda I) = \begin{vmatrix} 1 - \lambda & 2 & 2 \\ 2 & 1 - \lambda & 2 \\ 2 & 1 & 2 - \lambda \end{vmatrix} $

Menggunakan ekspansi kofaktor pada baris pertama:

$
\det(A - \lambda I) = (1 - \lambda) \begin{vmatrix} 1 - \lambda & 2 \\ 1 & 2 - \lambda \end{vmatrix} - 2 \begin{vmatrix} 2 & 2 \\ 2 & 2 - \lambda \end{vmatrix} + 2 \begin{vmatrix} 2 & 1 - \lambda \\ 2 & 1 \end{vmatrix}
$

Menghitung minor pertama:

$
\begin{vmatrix} 1 - \lambda & 2 \\ 1 & 2 - \lambda \end{vmatrix} = (1 - \lambda)(2 - \lambda) - 2 = \lambda^2 - 3\lambda + 2 - 2 = \lambda^2 - 3\lambda
$

Menghitung minor kedua:

$
\begin{vmatrix} 2 & 2 \\ 2 & 2 - \lambda \end{vmatrix} = 2(2 - \lambda) - 4 = 4 - 2\lambda - 4 = -2\lambda
$

Menghitung minor ketiga:

$
\begin{vmatrix} 2 & 1 - \lambda \\ 2 & 1 \end{vmatrix} = 2 - 2(1 - \lambda) = 2 - 2 + 2\lambda = 2\lambda
$

Jadi,

$
\det(A - \lambda I) = (1 - \lambda)(\lambda^2 - 3\lambda) - 2(-2\lambda) + 2(2\lambda)
$

$
= (1 - \lambda)(\lambda^2 - 3\lambda) + 4\lambda + 4\lambda
$

$
= (1 - \lambda)\lambda(\lambda - 3) + 8\lambda
$

$
= \lambda(\lambda - 3)(1 - \lambda) + 8\lambda
$

$
= -\lambda^3 + 4\lambda^2 + 5\lambda
$

Setara dengan:

$\lambda^3 - 4\lambda^2 - 5\lambda = 0 $

Menguraikan:

$\lambda (\lambda^2 - 4\lambda - 5) = 0 $

Kita selesaikan persamaan kuadrat $\lambda^2 - 4\lambda - 5 = 0$:

$\lambda^2 - 4\lambda - 5 = 0 $

$
\lambda = \frac{4 \pm \sqrt{16 + 20}}{2}
$
$
\lambda = \frac{4 \pm \sqrt{36}}{2}
$
$
\lambda = \frac{4 \pm 6}{2}
$

Jadi, kita mendapatkan tiga nilai eigen:

$
\lambda_1 = 0, \quad \lambda_2 = 5, \quad \lambda_3 = -1
$

Langkah 2: Temukan Vektor Eigen

Untuk setiap nilai eigen, kita substitusi $\lambda$ ke dalam $A - \lambda I$ dan mencari vektor eigen yang memenuhi $(A - \lambda I)\mathbf{v} = 0$.

Untuk $\lambda_1 = 0$:

$A - 0I = \begin{bmatrix} 1 & 2 & 2 \\ 2 & 1 & 2 \\ 2 & 1 & 2 \end{bmatrix} $

Kita cari vektor eigen $\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}$ yang memenuhi:

$\begin{bmatrix} 1 & 2 & 2 \\ 2 & 1 & 2 \\ 2 & 1 & 2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} $

Dari sistem persamaan ini, kita dapat menyelesaikan dan menemukan bahwa vektor eigen untuk $\lambda_1 = 0$ adalah:

$\mathbf{v_1} = k \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}, \quad k \in \mathbb{R} $

Untuk $\lambda_2 = 5$:

$A - 5I = \begin{bmatrix} 1 - 5 & 2 & 2 \\ 2 & 1 - 5 & 2 \\ 2 & 1 & 2 - 5 \end{bmatrix} = \begin{bmatrix} -4 & 2 & 2 \\ 2 & -4 & 2 \\ 2 & 1 & -3 \end{bmatrix} $

Kita cari vektor eigen $\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}$ yang memenuhi:

$\begin{bmatrix} -4 & 2 & 2 \\ 2 & -4 & 2 \\ 2 & 1 & -3 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} $

Dari sistem persamaan ini, kita dapat menyelesaikan dan menemukan bahwa vektor eigen untuk $\lambda_2 = 5$ adalah:

$\mathbf{v_2} = k \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}, \quad k \in \mathbb{R} $

Untuk $\lambda_3 = -1$:

$A + I = \begin{bmatrix} 1 + 1 & 2 & 2 \\ 2 & 1 + 1 & 2 \\ 2 & 1 & 2 + 1 \end{bmatrix} = \begin{bmatrix} 2 & 2 & 2 \\ 2 & 2 & 2 \\ 2 & 1 & 3 \end{bmatrix} $

Kita cari vektor eigen $\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}$ yang memenuhi:

$\begin{bmatrix} 2 & 2 & 2 \\ 2 & 2 & 2 \\ 2 & 1 & 3 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} $

Dari sistem persamaan ini, kita dapat menyelesaikan dan menemukan bahwa vektor eigen untuk $\lambda_3 = -1$ adalah:

$\mathbf{v_3} = k \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}, \quad k \in \mathbb{R} $

In [2]:
# Perhitungan menggunakan numpy
import numpy as np
from numpy import linalg as LA

a = np.array([[1,2,2],[2,1,2],[2,1,2]])
print(a)
w, v = LA.eig(a)
print("e-value : \n",w)
print("e-vactor : \n",v.round())

[[1 2 2]
 [2 1 2]
 [2 1 2]]
e-value : 
 [-1.  5.  0.]
e-vactor : 
 [[-1.  1. -0.]
 [ 0.  1. -0.]
 [ 0.  1.  1.]]


### **Contoh Implementasi Eigenvalue dan Eigenvector**
Implementasi PCA melalui EVD dengan python :

In [3]:
import numpy as np

def pcaEVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)
    C = (X_centered.T @ X_centered) / (n - 1)
    e_vals, e_vecs = np.linalg.eig(C)
    
    idx = e_vals.argsort()[::-1]
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]
    
    return (X_centered @ e_vecs), e_vals, e_vecs

X = np.array([[1, 4], [2, 3]])

components, eigenvalues, eigenvectors = pcaEVD(X)

rounded_components = np.round(components)
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)
print("Eigenvectors:\n", rounded_eigenvectors)

Components:
 [[-1.  0.]
 [ 1. -0.]]
Eigenvalues:
 [1. 0.]
Eigenvectors:
 [[ 1.  1.]
 [-1.  1.]]
