# **MATRIK INVERSI**

### Pengertian :
Invers matriks adalah matriks yang, ketika dikalikan dengan matriks asalnya, menghasilkan matriks identitas. Matriks identitas adalah matriks persegi yang elemen-elemennya memiliki nilai 1 di diagonal utamanya dan 0 di tempat lainnya. Dalam simbol matematika, invers dari sebuah matriks A biasanya dilambangkan dengan A^-1.

Contoh : jika A adalah matriks asal, maka A × A^-1 = A^-1 × A = I, di mana I adalah matriks identitas. Invers matriks digunakan dalam berbagai bidang matematika dan ilmu terapan, seperti sistem persamaan linear, transformasi linear, dan pemrosesan sinyal.

### Sifat-sifat Matriks invers :
1. Hanya dimiliki oleh matriks persegi karna memiliki kolom dan baris yanng sama.
2. Hanya ada matriks non-singular. Determinannya tidak sama dengan 0.
3. Unik : Setiap matriks hanya memiliki satu matriks invers
4. Invers dari invers : Jika Z memiliki invers, maka inversnya adalah matriks Z itu sendiri. 
(Z^-1)^-1=Z
5. Invers dari hasil kali : Jika Y dan Z adalah matriks yang memiliki invers, maka hasil kali AB juga memiliki invers, dan invernya adalah hasil kali invers secara terbalik. 
(YZ)^-1=(Z^-1)Y^-1
6. Invers dari tranpose : jika Z merupakan matriks persegi yang memiliki invers dari tranposenya adalah tranpose dari inversnya. 
(Z^T)^-1=(Z^-1)^T
7. Invers dari matriks identitas : Invers dari matriks identitas I adalah I itu sendiri


In [1]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

#### Persamaan 1

$$
\\4x_1 + 0x_2 + 0x_3 + 0x_4 = 4 \\
0x_1 + 0x_2 + 2x_3 + 0x_4 = 2 \\
0x_1 + 1x_2 + 2x_3 + 0x_4 = 3 \\
1x_1 + 0x_2 + 0x_3 + 1x_4 = 2 \\
\\
$$

In [2]:
# Contoh 1 :
a = np.array([[4,0,0,0,1,0,0,0],[0,0,2,0,0,1,0,0],[0,1,2,0,0,0,1,0],[1,0,0,1,0,0,0,1]])
print(a)

[[4 0 0 0 1 0 0 0]
 [0 0 2 0 0 1 0 0]
 [0 1 2 0 0 0 1 0]
 [1 0 0 1 0 0 0 1]]


In [3]:
# Mengalikan baris 0 dengan 1/4
b = RowScale(a, 0, 1/4)
print(b)

[[1.   0.   0.   0.   0.25 0.   0.   0.  ]
 [0.   0.   2.   0.   0.   1.   0.   0.  ]
 [0.   1.   2.   0.   0.   0.   1.   0.  ]
 [1.   0.   0.   1.   0.   0.   0.   1.  ]]


In [4]:
#Menukar baris ke 1 dan ke 2
c = RowSwap(b, 1, 2)
print(c)

[[1.   0.   0.   0.   0.25 0.   0.   0.  ]
 [0.   1.   2.   0.   0.   0.   1.   0.  ]
 [0.   0.   2.   0.   0.   1.   0.   0.  ]
 [1.   0.   0.   1.   0.   0.   0.   1.  ]]


In [5]:
# Menambah baris 1 dengan baris 2 yang sudah dikalikan dengan -1
d = RowAdd(c, 2, 1, -1)
print(d)

[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -1.    1.    0.  ]
 [ 0.    0.    2.    0.    0.    1.    0.    0.  ]
 [ 1.    0.    0.    1.    0.    0.    0.    1.  ]]


In [6]:
# Mengalikan baris 2 dengan 1/2
f = RowScale(d, 2, 1/2)
print(f)

[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -1.    1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.5   0.    0.  ]
 [ 1.    0.    0.    1.    0.    0.    0.    1.  ]]


In [7]:
# Menambah baris ke 3 dengan baris ke 0 yang sudah dikalikan dengan -1
g = RowAdd(f, 0, 3, -1)
print(g)

[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -1.    1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.5   0.    0.  ]
 [ 0.    0.    0.    1.   -0.25  0.    0.    1.  ]]


In [8]:
# Mencari x1, x2, x3, x4
h = np.array([[0.25,0,0,0], [0,-1,1,0], [0,0.5,0,0], [-0.25,0,0,1]])
j = np.array([[4], [2], [3], [2]])
print(h@j)

[[1.]
 [1.]
 [1.]
 [1.]]


In [9]:
# pembuktian
h = np.array([[0.25,0,0,0], [0,-1,1,0], [0,0.5,0,0], [-0.25,0,0,1]])
a = np.array([[4,0,0,0],[0,0,2,0],[0,1,2,0],[1,0,0,1]])
print(a@h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Persamaan 2 :
$$
\\0x_1 + 0x_2 + 0x_3 + 1x_4 = -3\\
4x_1 + 2x_2 + 0x_3 + (-4)x_4 = 22\\
(-2)x_1 + 0x_2 + 1x_3 + 2x_4 = -5\\
1x_1 + 0x_2 + 0x_3 + 1x_4 = -1\\
$$

In [10]:
# Contoh 2 :
a2 = np.array([[0,0,0,1,1,0,0,0], [4,2,0,-4,0,1,0,0], [-2,0,1,2,0,0,1,0], [1,0,0,1,0,0,0,1]])
print(a2)

[[ 0  0  0  1  1  0  0  0]
 [ 4  2  0 -4  0  1  0  0]
 [-2  0  1  2  0  0  1  0]
 [ 1  0  0  1  0  0  0  1]]


In [11]:
# Menukar baris ke 0 dengan baris ke 3
b2 = RowSwap(a2, 0, 3)
print(b2)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 4.  2.  0. -4.  0.  1.  0.  0.]
 [-2.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [12]:
# Menambah baris 1 dengan baris 0 yang telah dikalikan dengan -4
c2 = RowAdd(b2, 0, 1, -4)
print(c2)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  2.  0. -8.  0.  1.  0. -4.]
 [-2.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [13]:
# Menambah baris 2 dengan baris 0 yang telah dikalikan dengan 2
d2 = RowAdd(c2, 0, 2, 2)
print(d2)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  2.  0. -8.  0.  1.  0. -4.]
 [ 0.  0.  1.  4.  0.  0.  1.  2.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [14]:
# Mengalikan baris 1 dengan 1/2
e2 = RowScale(d2, 1, 1/2)
print(e2)

[[ 1.   0.   0.   1.   0.   0.   0.   1. ]
 [ 0.   1.   0.  -4.   0.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [15]:
# Menambah baris 0 dengan baris 3 yang telah dikalikan dengan -1
f2 = RowAdd(e2, 3, 0, -1)
print(f2)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.  -4.   0.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [16]:
# Menambah baris 1 dengan baris 3 yang telah dikalikan dengan 4
g2 = RowAdd(f2, 3, 1, 4)
print(g2)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.   0.   4.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [17]:
# Menambah baris 2 dengan baris 3 yang telah dikalikan dengan -4
h2 = RowAdd(g2, 3, 2, -4)
print(h2)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.   0.   4.   0.5  0.  -2. ]
 [ 0.   0.   1.   0.  -4.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [18]:
# Mencari x1, x2, x3, x4
h2 = np.array([[-1,0,0,1], [4,0.5,0,-2], [-4,0,1,2], [1,0,0,0]])
j = np.array([[-3], [22], [-5], [-1]])
print(h2@j)

[[ 2.]
 [ 1.]
 [ 5.]
 [-3.]]


In [19]:
# Pembuktian
h2 = np.array([[0,0,0,1], [4,2,0,-4], [-2,0,1,2], [1,0,0,1]])
k = np.array([[-1,0,0,1], [4,0.5,0,-2], [-4,0,1,2], [1,0,0,0]])
print(h2@k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Persamaan 3 :
$$
\\3x_1 + 2x_2 + 1x_3 + 0x_4 = -3\\
0x_1 + 1x_2 + 1x_3 + 0x_4 = 22\\
2x_1 + 1x_2 + 1x_3 + 0x_4 = -5\\
0x_1 + 2x_2 + 4x_3 + 1x_4 = -1\\
$$

In [20]:
# Contoh 3 :
a3 = np.array([[3,2,1,0,1,0,0,0], [0,1,1,0,0,1,0,0], [2,1,1,0,0,0,1,0], [0,2,4,1,0,0,0,1]])
print(a3)

[[3 2 1 0 1 0 0 0]
 [0 1 1 0 0 1 0 0]
 [2 1 1 0 0 0 1 0]
 [0 2 4 1 0 0 0 1]]


In [21]:
# Menambah baris 0 dengan baris 2 yang telah dikalikan dengan -1
b3 = RowAdd(a3, 2, 0, -1)
print(b3)

[[ 1.  1.  0.  0.  1.  0. -1.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.]
 [ 2.  1.  1.  0.  0.  0.  1.  0.]
 [ 0.  2.  4.  1.  0.  0.  0.  1.]]


In [22]:
# Menambah baris 2 dengan baris 0 yang telah dikalikan dengan -2
c3 = RowAdd(b3, 0, 2, -2)
print(c3)

[[ 1.  1.  0.  0.  1.  0. -1.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0. -1.  1.  0. -2.  0.  3.  0.]
 [ 0.  2.  4.  1.  0.  0.  0.  1.]]


In [23]:
# Menambah baris 0 dengan baris 1 yang telah dikalikan dengan -1
d3 = RowAdd(c3, 1, 0, -1)
print(d3)

[[ 1.  0. -1.  0.  1. -1. -1.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0. -1.  1.  0. -2.  0.  3.  0.]
 [ 0.  2.  4.  1.  0.  0.  0.  1.]]


In [24]:
# Menambah baris 2 dengan baris 1 yang telah dikalikan dengan 1
e3 = RowAdd(d3, 1, 2, 1)
print(e3)

[[ 1.  0. -1.  0.  1. -1. -1.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0.  0.  2.  0. -2.  1.  3.  0.]
 [ 0.  2.  4.  1.  0.  0.  0.  1.]]


In [25]:
# menambah baris 3 dengan baris 1 yang telah dikalikan dengan -2
f3 = RowAdd(e3, 1, 3, -2)
print(f3)

[[ 1.  0. -1.  0.  1. -1. -1.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0.  0.  2.  0. -2.  1.  3.  0.]
 [ 0.  0.  2.  1.  0. -2.  0.  1.]]


In [26]:
# Mengalikan baris 2 dengan 1/2
g3 = RowScale(f3, 2, 1/2)
print(g3)

[[ 1.   0.  -1.   0.   1.  -1.  -1.   0. ]
 [ 0.   1.   1.   0.   0.   1.   0.   0. ]
 [ 0.   0.   1.   0.  -1.   0.5  1.5  0. ]
 [ 0.   0.   2.   1.   0.  -2.   0.   1. ]]


In [27]:
# Menambah baris 0 dengan baris 2 yang telah dikalikan dengan 1
h3 = RowAdd(g3, 2, 0, 1)
print(h3)

[[ 1.   0.   0.   0.   0.  -0.5  0.5  0. ]
 [ 0.   1.   1.   0.   0.   1.   0.   0. ]
 [ 0.   0.   1.   0.  -1.   0.5  1.5  0. ]
 [ 0.   0.   2.   1.   0.  -2.   0.   1. ]]


In [28]:
# Menambah baris 1 dengan baris 2 yang telah dikalikan dengan -1
i3 = RowAdd(h3, 2, 1, -1)
print(i3)

[[ 1.   0.   0.   0.   0.  -0.5  0.5  0. ]
 [ 0.   1.   0.   0.   1.   0.5 -1.5  0. ]
 [ 0.   0.   1.   0.  -1.   0.5  1.5  0. ]
 [ 0.   0.   2.   1.   0.  -2.   0.   1. ]]


In [29]:
# Menambah baris 3 dengan baris 2 yang telah dikalikan dengan -2
j3 = RowAdd(i3, 2, 3, -2)
print(j3)

[[ 1.   0.   0.   0.   0.  -0.5  0.5  0. ]
 [ 0.   1.   0.   0.   1.   0.5 -1.5  0. ]
 [ 0.   0.   1.   0.  -1.   0.5  1.5  0. ]
 [ 0.   0.   0.   1.   2.  -3.  -3.   1. ]]


In [30]:
# Mencari x1, x2, x3, x4
h3 = np.array([[0, -0.5, 0.5, 0], [1, 0.5, -1.5, 0], [-1, 0.5, 1.5, 0], [2, -3, -3, 1]])
m = np.array([[5], [5], [3], [15]])
print(h3@m)

[[-1.]
 [ 3.]
 [ 2.]
 [ 1.]]


In [31]:
# Pembuktian
a3 = np.array([[3,2,1,0], [0,1,1,0], [2,1,1,0], [0,2,4,1]])
h3 = np.array([[0, -0.5, 0.5, 0], [1, 0.5, -1.5, 0], [-1, 0.5, 1.5, 0], [2, -3, -3, 1]])
print(a3@h3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
