# **ALJABAR MATRIKS**

### **Pengertian Matriks:**
Matriks adalah susunan bilagan real(atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk persegi ataupun persegi panjang. Setiap elemen memiliki posisi unik dalam matriks, ditentukan oleh baris dan kolomnya. Misalnya, matriks 2x3 memiliki 2 baris dan 3 kolom. suatu matriks biasa diberi nama dengan menggunakan huruf kapital (seperti A, B dll) dan elemennya dinyatakan dengan huruf kecil.



 Berikut Contoh Matriks :

$$
\begin{equation} A = 
\left[ \begin{array}{cccc} 3&1&4\\
5&2&1\\
2&8&5 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} B = 
\left[ \begin{array}{cccc} -4&0&8\\
0&7&9\\
3&6&1 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} c = 
\left[ \begin{array}{cccc} 8&9\\
4&0\\
9&2 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} c = 
\left[ \begin{array}{cccc}1&5&8\\
2&9&6\\
7&6&0 \end{array}\right]
\end{equation}
$$


## **Implementasi dengan Numpy**

Saat array dibuat, informasi ini disimpan sebagai bagian dari  objek array dan dapat diakses dengan metode yang disebut shape. Jika C adalah sebuah array, objek C.shape itu sendiri adalah sebuah array yang memiliki dua nilai masukan. Yang pertama (dengan indeks 0!) adalah jumlah baris, dan yang kedua (dengan indeks 1!) adalah jumlah kolom.



In [2]:
import numpy as np
A = np.array([[3, 1, 4],[5, 2, 1],[2, 8, 5]])
B = np.array([[-4, 0, 8],[0, 7, 9],[3, 6, 1]])
C = np.array([[8, 9],[4, 0],[9, 2]])
D = np.array([[1, 5, 8],[2, 9, 6],[7, 6, 0]])
print(A)
print(C.shape) # digunakan untuk melihat banyak baris dan kolom

[[3 1 4]
 [5 2 1]
 [2 8 5]]
(3, 2)


## **Operasi pada Matriks**
Operasi matriks adalah serangkaian operasi atau tindakan yang dilakukan pada matriks, baik itu untuk mengubah matriks ataupun menggabungkan matriks. Berikut beberapa operasi matriks yang sering digunakan:


### **1. Penjumlahan Matriks :**

Operasi ini melibatkan penambahan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENJUMLAHAN MATRIKS A + B :

$$
\begin{equation} A = 
\left[ \begin{array}{cccc} 3&1&4\\
5&2&1\\
2&8&5 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} B = 
\left[ \begin{array}{cccc} -4&0&8\\
0&7&9\\
3&6&1 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} A + B = 
\left[ \begin{array}{cccc}
3+(-4)&1+0&4+8\\
5+0&2+7&1+9\\
2+3&8+6&5+1 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} = 
\left[ \begin{array}{cccc} -1&1&12\\
5&9&10\\
5&14&6\end{array}\right]
\end{equation}
$$

BERIKUT PROGRAM UNTUK PENJUMLAHAN MATRIKS:



In [3]:
print('A+B=\n',A+B)
print('B+A=\n',B+A)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[-1  1 12]
 [ 5  9 10]
 [ 5 14  6]]
B+A=
 [[-1  1 12]
 [ 5  9 10]
 [ 5 14  6]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


### **2. Pengurangan Matriks:**

Operasi ini melibatkan pengurangan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENGURANGAN MATRIKS:

$$
\begin{equation} A = 
\left[ \begin{array}{cccc} 3&1&4\\
5&2&1\\
2&8&5 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} B = 
\left[ \begin{array}{cccc} -4&0&8\\
0&7&9\\
3&6&1 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} A - B = 
\left[ \begin{array}{cccc}
3-(-4)&1-0&4-8\\
5-0&2-7&1-9\\
2-3&8-6&5-1\end{array}\right]
\end{equation}
$$

$$
\begin{equation} = 
\left[ \begin{array}{cccc} 7&1&4\\
5&-5&-8\\
-1&2&4\end{array}\right]
\end{equation}
$$


BERIKUT PROGRAM UNTUK PENGURANGAN MATRIKS:

In [4]:
print('A-B=\n', A-B)
print('B-A=\n', B-A)
print('Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A')

A-B=
 [[ 7  1 -4]
 [ 5 -5 -8]
 [-1  2  4]]
B-A=
 [[-7 -1  4]
 [-5  5  8]
 [ 1 -2 -4]]
Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A


### **3. Perkalian Matriks:**

Operasi ini melibatkan perkalian elemen-elemen matriks. Untuk melakukan perkalian matriks A dan B, jumlah kolom dalam matriks A harus sama dengan jumlah baris dalam matriks B. Contoh matriks A memiliki ordo atau ukuran mxn, maka matriks B harus memiliki ordo atau ukuran nxp. Sehingga hasil dari perkalian tersebut akan menghasilkan matriks baru dengan ukuran mxp. Hasilnya akan memiliki jumlah baris yang sama dengan matriks A dan jumlah kolom yang sama dengan matriks B.

CONTOH PERKALIAN MATRIKS:

$$
\begin{equation} A = 
\left[ \begin{array}{cccc} 3&1&4\\
5&2&1\\
2&8&5 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} B = 
\left[ \begin{array}{cccc} -4&0&8\\
0&7&9\\
3&6&1 \end{array}\right]
\end{equation}
$$

$$
\begin{equation} A x B = 
\left[ \begin{array}{cccc}
3(-4)+1(0)+4(3) &3(0)+1(7)+4(6) &3(8)+1(9)+4(1)\\
5(-4)+2(0)+1(3) &5(0)+2(7)+1(6) &5(8)+2(9)+1(1)\\
2(-4)+8(0)+5(3) &2(0)+8(7)+5(6) &2(8)+8(9)+5(1)\end{array}\right]
\end{equation}
$$

$$
\begin{equation} = 
\left[ \begin{array}{cccc} 
0&31&37\\
-17&20&59\\
7&86&93\end{array}\right]
\end{equation}
$$


BERIKUT PROGRAM UNTUK PERKALIAN MATRIKS:

In [5]:
print('A*B=\n',A@B)
print('A*C=\n',A@C)
print('B*C=\n',B@C)

A*B=
 [[  0  31  37]
 [-17  20  59]
 [  7  86  93]]
A*C=
 [[64 35]
 [57 47]
 [93 28]]
B*C=
 [[ 40 -20]
 [109  18]
 [ 57  29]]


- Sifat Asosiasi:

  (AB)C = A(BC)

In [6]:
print('A(BC) =\n', A@(B@C))
print('(AB)C =\n',(A@B)@C)

A(BC) =
 [[ 457   74]
 [ 475  -35]
 [1237  249]]
(AB)C =
 [[ 457   74]
 [ 475  -35]
 [1237  249]]


- Perkalian skalar:

  c(AB) = (cA)B = A(cB)

In [7]:
c = 3
print('c(AB) =\n',c*(A@B))
print('(cA)B =\n',(c*A)@B)
print('A(cB) =\n',A@(c*B))

c(AB) =
 [[  0  93 111]
 [-51  60 177]
 [ 21 258 279]]
(cA)B =
 [[  0  93 111]
 [-51  60 177]
 [ 21 258 279]]
A(cB) =
 [[  0  93 111]
 [-51  60 177]
 [ 21 258 279]]


- Perkalian identitas:

  AI = IA = A

In [8]:
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',A@i)
print('IA=\n',i@A)
print('A=\n',A)

AI=
 [[3 1 4]
 [5 2 1]
 [2 8 5]]
IA=
 [[3 1 4]
 [5 2 1]
 [2 8 5]]
A=
 [[3 1 4]
 [5 2 1]
 [2 8 5]]


- Tidak berlaku sifat kumutatif:

  AB != BA atau AB tidak sama dengan BA

In [9]:
print('AB=\n',A@B)
print('BA=\n',B@A)

AB=
 [[  0  31  37]
 [-17  20  59]
 [  7  86  93]]
BA=
 [[ 4 60 24]
 [53 86 52]
 [41 23 23]]


### **4. Transpose Matriks**

Transpose matriks adalah matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya. Jika sebuah matriks berukuran M X N, maka transpose matriks tersebut memiliki ordo N X M.

CONTOH TRANSPOSE MATRIKS:

$$
\begin{equation} C = 
\left[ \begin{array}{cccc}
8&9\\
4&0\\
9&2\end{array}\right]
\end{equation}
$$

$$
\begin{equation} CT (C Transposre) =
\left[ \begin{array}{cccc}
8&4&9\\
9&0&2\end{array}\right]
\end{equation}
$$


BERIKUT PROGRAM UNTUK MENG-TRANSPOSE MATRIKS:

In [10]:
C_T = C.transpose()
print(C_T)

[[8 4 9]
 [9 0 2]]


In [11]:
Z = C_T @ C
print('Z = C_transpose x C =\n',Z)
print('ordo z adalah',Z.shape)
Y = C @ C_T
print('P = C x C_transpose =\n',Y)
print('ordo P adalah',Y.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

Z = C_transpose x C =
 [[161  90]
 [ 90  85]]
ordo z adalah (2, 2)
P = C x C_transpose =
 [[145  32  90]
 [ 32  16  36]
 [ 90  36  85]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


## **Program Perkalian Matriks**

In [16]:
def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

perkalian(A,B)

[[0, 31, 37], [-17, 20, 59], [7, 86, 93]]